/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConttractList: typeof import('./src/components/list/ConttractList.vue')['default']
    FooterTabbar: typeof import('./src/components/FooterTabbar.vue')['default']
    LuckyMoney: typeof import('./src/components/luckyMoney/index.vue')['default']
    Luckyspin: typeof import('./src/components/luckyspin/index.vue')['default']
    Main: typeof import('./src/components/luckyMoney/main.vue')['default']
    MessageList: typeof import('./src/components/list/MessageList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TalentList: typeof import('./src/components/list/TalentList.vue')['default']
    TaskList: typeof import('./src/components/list/TaskList.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanIcon: typeof import('vant/es')['Icon']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
